---
abstract: 'Find out what modules are used'
author:
  - 'Thomas Klausner <domm@zsi.at>'
build_requires:
  Test::Deep: 0.087
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  UNIVERSAL::require: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-ExtractUse
provides:
  Module::ExtractUse:
    file: lib/Module/ExtractUse.pm
    version: 0.24
  Module::ExtractUse::Grammar:
    file: lib/Module/ExtractUse/Grammar.pm
    version: 0
  Parse::RecDescent::Module::ExtractUse::Grammar:
    file: lib/Module/ExtractUse/Grammar.pm
    version: 0
requires:
  Parse::RecDescent: 1.94
  Pod::Strip: 1.00
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.24
