#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-ExtractUse
version:      0.05
version_from: ExtractUse.pm
installdirs:  site
requires:
    Pod::Simple:                   0
    Parse::RecDescent:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_02
