---
abstract: 'Find out what modules are used'
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::Deep: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200014, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-ExtractUse
requires:
  Carp: 0
  Parse::RecDescent: 1.967009
  Pod::Strip: 0
  perl: 5.008
  vars: 0
  version: 0
resources:
  repository: git://github.com/domm/Module-ExtractUse.git
version: 0.27
