---
name: Module-ExtractUse
version: 0.16
author:
  - Thomas Klausner <domm@zsi.at>
abstract: Find out what modules are used
license: perl
requires:
  Parse::RecDescent: 1.94
  Pod::Simple: 3.00
  Test::Deep: 0.087
  Test::More: 0
  Test::NoWarnings: 0
provides:
  Module::ExtractUse:
    file: lib/Module/ExtractUse.pm
    version: 0.16
  Module::ExtractUse::Grammar:
    file: lib/Module/ExtractUse/Grammar.pm
  Parse::RecDescent::Module::ExtractUse::Grammar:
    file: lib/Module/ExtractUse/Grammar.pm
generated_by: Module::Build version 0.2609
